version: '3'

services:
  database:
    image: postgres:latest
    container_name: postgres_db
    command: --init-file /database_utils/init.sql
    volumes:
      - db-data:/var/lib/postgresql/data \
      - ./database_utils/init.sql
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local
