version: '3'

services:
  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
    ports:
      - "5431:5431"

volumes:
  db-data:
    driver: local
