version: '3'

services:
  app:
    image: overdose-analysis:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./output:/var/app/output"
      - "./logs:/var/app/logs"
    environment:
      - SOCRATA_TOKEN

volumes:
  logs:
  output:
  data:
    driver: local

