version: '3'

services:
  app:
    image: overdose-analysis:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./data:/var/app/data"
      - "./logs:/var/app/logs"
    environment:
      - SOCRATA_TOKEN
